# Generated by Django 4.1.3 on 2022-12-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_profile',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='t_profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='t_profile',
            name='biodata',
        ),
        migrations.RemoveField(
            model_name='t_profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='t_profile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='t_profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='t_profile',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='t_profile',
            name='religion',
        ),
        migrations.AddField(
            model_name='t_profile',
            name='designation',
            field=models.CharField(choices=[('PROFESSOR', 'PROFESSOR'), ('ASSISTANT PROFESSOR', 'ASSISTANT PROFESSOR'), ('LECTURER', 'LECTURER')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='t_profile',
            name='expertise',
            field=models.CharField(choices=[('RESEARCH', 'RESEARCH'), ('THESIS', 'THESIS')], max_length=50, null=True),
        ),
    ]
